name: Auto update Site using Hugo

on:
  push:
    branches:
      - site

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        # with:
        #   submodules: true

      - name: Trigger Cloudflage Pages Build
        run: curl -X POST ${{ secrets.CF_PAGES_BUILD_WEBHOOK_URL }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.1'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          commit_message: ${{ github.event.head_commit.message }}
